language: groovy

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

install: 
  - pip install --user -r requirements.txt

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - bin/coveralls -v

after_sucess:
  - echo $TRAVIS_TEST_RESULT